# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 13:01
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=geoposition.fields.GeopositionField(default=(1, 10.730819900000029), max_length=42),
        ),
    ]
