# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 13:27
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
