# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160905_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='TypeOfMovement',
            field=models.IntegerField(choices=[(1, 'Falls'), (2, 'Topples'), (3, 'Slides'), (4, 'Spreads'), (5, 'Flows')], default=1),
        ),
    ]
