# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_typeofmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='DepthOfMovement',
            field=models.IntegerField(choices=[(1, 'Superficial (< 0.5 m)'), (2, 'Shallow (0.5 to 3 m)'), (3, 'Medium (3 to 8 m)'), (4, 'Deep (8 to 15 m)'), (5, 'Very deep (> 15 m)')], default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='Groundwater',
            field=models.IntegerField(choices=[(1, 'Artesian'), (2, 'High'), (3, 'Low'), (4, 'Absent')], default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='Material',
            field=models.IntegerField(choices=[(1, 'Earth'), (2, 'Debris'), (3, 'Rock')], default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='RateOfMovementAtTimeOfWorks',
            field=models.IntegerField(choices=[(1, 'Moderate to fast'), (2, 'Slow'), (3, 'Very slow'), (4, 'Extremely slow')], default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='SurfaceWater',
            field=models.IntegerField(choices=[(1, 'Rain'), (2, 'Snowmelt'), (3, 'Localized'), (4, 'Stream'), (5, 'Torrent'), (6, 'River')], default=1),
        ),
    ]
