# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160905_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedMeasures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category_id', models.IntegerField(default=0)),
                ('sub_id', models.IntegerField(default=0)),
                ('selected_tech_criteria', models.CommaSeparatedIntegerField(max_length=200)),
                ('performance_and_reliability_criteria', models.CommaSeparatedIntegerField(max_length=200)),
                ('sum_tech_criteria', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StructuralMeasures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category_id', models.IntegerField(default=0)),
                ('sub_id', models.IntegerField(default=0)),
                ('tech_criteria_AtoF', models.CommaSeparatedIntegerField(max_length=200)),
                ('performance_and_reliability_criteria', models.CommaSeparatedIntegerField(max_length=200)),
            ],
        ),
    ]
