# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_selectedmeasures_structuralmeasures'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='available_measures_category_id',
            field=models.CommaSeparatedIntegerField(default=[], max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='available_measures_sub_id',
            field=models.CommaSeparatedIntegerField(default=[], max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='available_measures_sum_tech_criteria',
            field=models.CommaSeparatedIntegerField(default=[], max_length=200),
        ),
    ]
