# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160907_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedMeasures',
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='category_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='description_text',
            field=models.TextField(default='will be updated'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='design_text',
            field=models.TextField(default='will be updated'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='reference',
            field=models.TextField(default='will be updated'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
