# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160913_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralmeasures',
            name='figure_captions',
            field=models.CommaSeparatedIntegerField(default=[], max_length=200),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='img_src',
            field=models.CommaSeparatedIntegerField(default=[], max_length=200),
        ),
    ]
