# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_categories_descrption_id_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories_descrption',
            old_name='id_field',
            new_name='number',
        ),
    ]
