# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160915_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuralmeasures',
            name='category_description2',
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='category_description',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Categories_descrption'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='figure_captions',
            field=models.CommaSeparatedIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='img_src',
            field=models.CommaSeparatedIntegerField(max_length=200),
        ),
    ]
