# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160915_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_1_1',
            field=models.IntegerField(default=0, verbose_name='TypeOfMovement:Falls'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_1_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_1_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_1_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_1_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_2_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_2_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_2_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_3_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_3_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_3_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_3_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_3_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_4_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_4_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_4_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_4_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_5_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_5_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_5_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_6_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_6_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_6_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_6_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_6_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_6_6',
            field=models.IntegerField(default=0),
        ),
    ]
