# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160915_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_5_4',
            field=models.IntegerField(default=0, verbose_name='Rate:5_Absent'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_1_1',
            field=models.IntegerField(default=0, verbose_name='Rate:1_Falls'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_1_2',
            field=models.IntegerField(default=0, verbose_name='Rate:1_Topples'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_1_3',
            field=models.IntegerField(default=0, verbose_name='Rate:1_Slides'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_1_4',
            field=models.IntegerField(default=0, verbose_name='Rate:1_Spreads'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_1_5',
            field=models.IntegerField(default=0, verbose_name='Rate:1_Flows'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_2_1',
            field=models.IntegerField(default=0, verbose_name='Rate:2_Earth'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_2_2',
            field=models.IntegerField(default=0, verbose_name='Rate:2_Debris'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_2_3',
            field=models.IntegerField(default=0, verbose_name='Rate:2_Rock'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_3_1',
            field=models.IntegerField(default=0, verbose_name='Rate:3_Superficial'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_3_2',
            field=models.IntegerField(default=0, verbose_name='Rate:3_Shallow'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_3_3',
            field=models.IntegerField(default=0, verbose_name='Rate:3_Medium'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_3_4',
            field=models.IntegerField(default=0, verbose_name='Rate:3_Deep '),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_3_5',
            field=models.IntegerField(default=0, verbose_name='Rate:3_VeryDeep'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_4_1',
            field=models.IntegerField(default=0, verbose_name='Rate:4_ModeratelyToFast'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_4_2',
            field=models.IntegerField(default=0, verbose_name='Rate:4_Slow'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_4_3',
            field=models.IntegerField(default=0, verbose_name='Rate:4_VerySlow'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_4_4',
            field=models.IntegerField(default=0, verbose_name='Rate:4_ExtremelySlow'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_5_1',
            field=models.IntegerField(default=0, verbose_name='Rate:5_Artesian'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_5_2',
            field=models.IntegerField(default=0, verbose_name='Rate:5_High'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_5_3',
            field=models.IntegerField(default=0, verbose_name='Rate:5_Low'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_6_1',
            field=models.IntegerField(default=0, verbose_name='Rate:6_Rain'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_6_2',
            field=models.IntegerField(default=0, verbose_name='Rate:6_Snowmelt'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_6_3',
            field=models.IntegerField(default=0, verbose_name='Rate:6_Localized'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_6_4',
            field=models.IntegerField(default=0, verbose_name='Rate:6_Stream'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_6_5',
            field=models.IntegerField(default=0, verbose_name='Rate:6_Torrent'),
        ),
        migrations.AlterField(
            model_name='structuralmeasures',
            name='tech_6_6',
            field=models.IntegerField(default=0, verbose_name='Rate:6_River'),
        ),
    ]
