# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20160915_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='available_measures_category_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='available_measures_sub_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='available_measures_sum_tech_criteria',
        ),
        migrations.AddField(
            model_name='post',
            name='available_measures',
            field=models.ManyToManyField(to='blog.StructuralMeasures'),
        ),
    ]
