# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160915_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='available_measures_sum_tech_criteria',
            field=models.CommaSeparatedIntegerField(default=0, max_length=200),
        ),
    ]
