# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_available_measures_sum_tech_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuralmeasures',
            name='performance_and_reliability_criteria',
        ),
        migrations.RemoveField(
            model_name='structuralmeasures',
            name='tech_criteria_AtoF',
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='note_tech_1',
            field=models.TextField(default='will be updated', verbose_name='Note_applicability_TypeOfMovement'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='note_tech_10',
            field=models.TextField(default='will be updated', verbose_name='Note_applicability_TypicalCost'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='note_tech_2',
            field=models.TextField(default='will be updated', verbose_name='Note_applicability_Material'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='note_tech_3',
            field=models.TextField(default='will be updated', verbose_name='Note_applicability_DepthOfMovement'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='note_tech_4',
            field=models.TextField(default='will be updated', verbose_name='Note_applicability_RateOfMovement'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='note_tech_5',
            field=models.TextField(default='will be updated', verbose_name='Note_applicability_Groundwater'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='note_tech_6',
            field=models.TextField(default='will be updated', verbose_name='Note_applicability_SurfaceWater'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='note_tech_7',
            field=models.TextField(default='will be updated', verbose_name='Note_applicability_Maturity'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='note_tech_8',
            field=models.TextField(default='will be updated', verbose_name='Note_applicability_Reliability'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='note_tech_9',
            field=models.TextField(default='will be updated', verbose_name='Note_applicability_Implementation'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_10',
            field=models.IntegerField(default=0, verbose_name='Rate:10 TypicalCost'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_7',
            field=models.IntegerField(default=0, verbose_name='Rate:7 Maturity'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_8',
            field=models.IntegerField(default=0, verbose_name='Rate:8 Reliability'),
        ),
        migrations.AddField(
            model_name='structuralmeasures',
            name='tech_9',
            field=models.IntegerField(default=0, verbose_name='Rate:9 Implementation'),
        ),
    ]
