# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20160919_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='selected_measures',
            field=models.ManyToManyField(related_name='selected_measures', to='blog.StructuralMeasures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Perform_weight_1',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='Maturity of technology'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Perform_weight_2',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='Reliability of performance'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Perform_weight_3',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='Reliability Uncertainty in design'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Perform_weight_4',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='Reliability Uncertainty in implementation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Perform_weight_5',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='Safety during construction'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Perform_weight_6',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='Service life required (durability)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Perform_weight_7',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='Aesthetics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Perform_weight_8',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='Typical cost'),
        ),
        migrations.AlterField(
            model_name='post',
            name='available_measures',
            field=models.ManyToManyField(related_name='available_measures', to='blog.StructuralMeasures'),
        ),
    ]
